### ISSUE TITLE
NPE checking attributes

### ISSUE THREAD

**Issue by stefanofornari** [awslabs/aws-java-nio-spi-for-s3#36]
The following simple snippet fails with the NPE below...

```
FileSystem s3 = FileSystems.newFileSystem(URI.create("s3://bucket"));

Stream<Path> stream = Files.walk(s3.getPath("/"));
for (Path path: stream.filter(Files::isRegularFile).toList()) {
    System.out.println(path);
}
```

ava.lang.NullPointerException: Cannot invoke "java.nio.file.attribute.BasicFileAttributes.isDirectory()" because "attrs" is null
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:288)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3917)
	at java.base/java.nio.file.Files.walk(Files.java:3972)

**Comment by markjschreiber** [comment]
The issue seems to be with https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/main/src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java#L755 which returns `null` if the path is a directory. I think this was an incorrect assumption on my part that directories wouldn't have attributes.

The line can probably be removed but we'd want to run some tests.

**Comment by markjschreiber** [comment]
Fixed in this commit https://github.com/awslabs/aws-java-nio-spi-for-s3/commit/bf14c036b66c7c574c24757523c6c2641164b3b6
