### ISSUE TITLE
S3Exception: the region 'eu-west-1' is wrong; expecting 'us-east-1'

### ISSUE THREAD

**Issue by heuermh** [awslabs/aws-java-nio-spi-for-s3#399]
Note may be a duplicate of #353.

With version 1.2.4, a warning is logged when the bucket region does not match the account region, but the downloaded succeeds
```
$ foo -i s3://ngi-igenomes/igenomes/Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.bed
[WARN] S3ClientStoreProvider - Unable to determine the region of bucket: 'ngi-igenomes'. Generating
a client for the profile region.
```

With version 2.0.0-rc1, `S3Exception` is thrown
```
$ foo -i s3://ngi-igenomes/igenomes/Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.bed
java.lang.RuntimeException: java.util.concurrent.ExecutionException:
software.amazon.awssdk.services.s3.model.S3Exception: The authorization header is malformed; the region
'eu-west-1' is wrong; expecting 'us-east-1' (Service: S3, Status Code: 400, Request ID: ..., Extended Request ID: .../...=)
	at software.amazon.nio.spi.s3.S3ClientProvider.generateClient(S3ClientProvider.java:133)
	at software.amazon.nio.spi.s3.S3FileSystem.readClient(S3FileSystem.java:422)
	at software.amazon.nio.spi.s3.S3SeekableByteChannel.<init>(S3SeekableByteChannel.java:68)
	at software.amazon.nio.spi.s3.S3SeekableByteChannel.<init>(S3SeekableByteChannel.java:40)
	at software.amazon.nio.spi.s3.S3FileSystemProvider.newByteChannel(S3FileSystemProvider.java:226)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:159)
	...
Caused by: java.util.concurrent.ExecutionException: software.amazon.awssdk.services.s3.model.S3Exception: The authorization header is malformed; the region 'eu-west-1' is wrong; expecting 'us-east-1' (Service: S3, Status Code: 400, Request ID: ..., Extended Request ID: .../...=)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at software.amazon.nio.spi.s3.S3ClientProvider.getBucketLocation(S3ClientProvider.java:200)
	at software.amazon.nio.spi.s3.S3ClientProvider.determineBucketLocation(S3ClientProvider.java:183)
	at software.amazon.nio.spi.s3.S3ClientProvider.getClientForBucket(S3ClientProvider.java:163)
	at software.amazon.nio.spi.s3.S3ClientProvider.generateClient(S3ClientProvider.java:150)
	at software.amazon.nio.spi.s3.S3ClientProvider.generateClient(S3ClientProvider.java:131)
	... 15 more
Caused by: software.amazon.awssdk.services.s3.model.S3Exception: The authorization header is malformed; the region 'eu-west-1' is wrong; expecting 'us-east-1' (Service: S3, Status Code: 400, Request ID: ..., Extended Request ID: .../...=)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:279)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:92)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:135)
	at software.amazon.awssdk.core.internal.metrics.BytesReadTrackingPublisher$BytesReadTracker.onComplete(BytesReadTrackingPublisher.java:74)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$DataCountingPublisher$1.onComplete(ResponseHandler.java:519)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:254)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$600(ResponseHandler.java:77)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:375)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.publishMessage(HandlerPublisher.java:402)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.flushBuffer(HandlerPublisher.java:338)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.receivedDemand(HandlerPublisher.java:291)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.access$200(HandlerPublisher.java:61)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:495)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by markjschreiber** [comment]
Cause seems to be that the ByteReader was creating an S3Client in the wrong region when it already had a Client (in the right region).

**Comment by markjschreiber** [comment]
Can you check if this is resolved by PR #400 ?

**Comment by heuermh** [comment]
Sure, I'm a little stuck by the gradle build, how do I build and install a snapshot to my local Maven repo?

**Comment by markjschreiber** [comment]
The project has a 'publishToMavenLocal' task that should do what you need.

**Comment by markjschreiber** [comment]
As an alternative you could probably add the built jar to your maven POM as a local jar. You would probably want the "fat" jar which is built with the `shadowJar` task otherwise you will need to provide all the dependencies yourself.

**Comment by heuermh** [comment]
Thanks!  Yes, I can confirm pull request #400 fixes this issue for me.

**Comment by markjschreiber** [comment]
Nice, I will merge it and close out this issue.

**Comment by heuermh** [comment]
Thank you, @markjschreiber!
