### ISSUE TITLE
Default StandardOpenOption.READ

### ISSUE THREAD

**Issue by senrajag** [awslabs/aws-java-nio-spi-for-s3#7]
If no OpenOption is provided, please default to StandardOpenOption.READ.

Exception in thread "main" java.io.IOException: Invalid channel mode
        at software.amazon.nio.spi.s3.S3SeekableByteChannel.<init>(S3SeekableByteChannel.java:100)
        at software.amazon.nio.spi.s3.S3SeekableByteChannel.<init>(S3SeekableByteChannel.java:66)
        at software.amazon.nio.spi.s3.S3FileSystemProvider.newByteChannel(S3FileSystemProvider.java:214)
        at software.amazon.nio.spi.s3.S3FileSystemProvider.newByteChannel(S3FileSystemProvider.java:195)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
        at java.base/java.nio.file.Files.newInputStream(Files.java:160)
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2922)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3412)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3453)
        at examples.Main.main(Main.java:42)

**Comment by markjschreiber** [comment]
Fixed in [c42ff6a](https://github.com/awslabs/aws-java-nio-spi-for-s3/commit/c42ff6ad89ce26b3671fdc7181d4f5619527ae97)

**Comment by markjschreiber** [comment]
@senrajag thanks for spotting this. I have committed a fix and test to main. Let me know if you still see problems

**Comment by senrajag** [comment]
@markjschreiber This works. Thank you for the quick fix.
