### ISSUE TITLE
IOException: Invalid channel mode when reading

### ISSUE THREAD

**Issue by heuermh** [awslabs/aws-java-nio-spi-for-s3#9]
Since upgrading from 1.1.1 to version 1.2.0 (commit https://github.com/heuermh/dishevelled-bio/commit/308916f4f7602551980d13277021eeb27fdd215f) I run into
```
$ foo -i s3://<bucket>/<path>.fastq.gz
...
java.io.IOException: Invalid channel mode
	at software.amazon.nio.spi.s3.S3SeekableByteChannel.<init>(S3SeekableByteChannel.java:100)
	at software.amazon.nio.spi.s3.S3SeekableByteChannel.<init>(S3SeekableByteChannel.java:66)
	at software.amazon.nio.spi.s3.S3FileSystemProvider.newByteChannel(S3FileSystemProvider.java:214)
	at software.amazon.nio.spi.s3.S3FileSystemProvider.newByteChannel(S3FileSystemProvider.java:195)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
```

Was there a default `OpenOption` or something similar present before that I'm missing now?

Thank you in advance.

**Comment by vicricker** [comment]
I have the same problem.  I reverted to 1.1.1.

**Comment by markjschreiber** [comment]
@heuermh @vicricker , I believe this should be fixed now in 1.2.1 (or HEAD). Can you test?

**Comment by heuermh** [comment]
Thank you, @markjschreiber, will do!

**Comment by markjschreiber** [comment]
Version 1.2.1 has also just been pushed to our Sonatype repo and should replicate to Maven Central in a few hours.
